% Based on code by:  Matt Fig, 2009 Mathworks File Exchange
%%
function calculatorGUI()
% Simple calculator
%the figure
fh = figure('units','pixels',...
    'position',[400 400 300 130],...
    'menubar','none',...
    'name','Basic Calculator',...
    'numbertitle','off',...
    'resize','off');
COL = get(fh,'color');
%pop-up, aka drop-down menu
dropDown = uicontrol('style','pop',...
    'unit','pix',...
    'position',[10 20 120 30],...
    'string',{'Add';'Multiply';'Subtract';'Divide';'Power'},... 
    'Callback', @updateOperator_call);
%first operand
operand1 = uicontrol('style','edit',...
    'unit','pix',...
    'position',[10 90 70 30],...
    'string','3');
%operator
op = uicontrol('style','text',...
    'unit','pix',...
    'position',[85 90 20 30],...
    'string','+',...
    'fontsize',16,...
    'backgroundcolor',COL);
%second operator
operand2 = uicontrol('style','edit',...
    'unit','pix',...
    'position',[110 90 70 30],...
    'string','2');
%label for equal sign
equalSign = uicontrol('style','text',...
    'unit','pix',...
    'position',[185 90 20 30],...
    'string','=',...
    'fontsize',16,...
    'backgroundcolor',COL);
%display the answer
answer = uicontrol('style','edit',...
    'unit','pix',...
    'position',[220 90 70 30],...
    'string','answer');
%calculate button
calculateButton = uicontrol('style','push',...
    'unit','pix',...
    'position',[160 20 120 30],...
    'string','Calculate', 'Callback', @pb_call);


    function updateOperator_call(~,~)
        % User's choice from popup.
        items = get(dropDown, 'String');  
        index_selected = get(dropDown,'Value');        
        item_selected = items{index_selected};        
        % operator string mappint to sign
        switch item_selected  
            case 'Add'
                str = '+';
            case 'Multiply'
                str = 'x';
            case 'Subtract'
                str = '-';
            case 'Divide'
                str = '/';
            case 'Power'
                str = '^';
            otherwise
        end
        %show the new operator sign
        set(op,'Visible','on','String',str);  % Set the operation display.        
    end
    function pb_call(~,~)
        N(1) = str2double (get(operand1, 'String'));
        N(2) = str2double (get(operand2, 'String'));
        % User's choice from popup.
        items = get(dropDown, 'String');  
        index_selected = get(dropDown,'Value');        
        item_selected = items{index_selected}; 
        
        % Now get the string updates and perform operations.
        switch item_selected  % User's string choice.
            case 'Add'
                A = sum(N);
            case 'Multiply'
                A = prod(N);
            case 'Subtract'
                A = -diff(N);
            case 'Divide'
                A = N(1)/N(2);
            case 'Power'
                A = N(1).^N(2);
        end         
        %show the answer
        set(answer,'String',A);       
    end
end
